# Site settings
title: NACIÓN UNITE # site title
description: >- # site description
 Torneos, Builds y mucho más!
lang: es # default lang
timezone: America/Mexico_City # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name:  # author name
  bio: >- # tell to the world
    
  username: username # general username
  github: github_username # github username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  email: your-email@email.com # email adress
  avatar: /assets/img/ # change with your own avatar

# URL settings
url: "https://xforceunite.site" #
baseurl:
permalink: /:title/
google_analytics: G-4M64EKVQ7H # leave it blank if not wish
fb_appid:


# --- Variables de Navegación Globales ---
links_navegacion:
  indigo: /liga-indigo-orion-ranking-junio2025
  supercxf: /super-copa-xforce
  copa: /copa-xforce-ad-gaming-edition
  sorteos: /sorteo-mensual

redes_sociales:
  twitch: https://www.twitch.tv/uniteforzestadium
  instagram: https://www.instagram.com/xf05__esports/
  x: https://x.com/XF05eSports
  facebook: https://www.facebook.com/ligaindigo.xf/
  discord: https://discord.gg/MqkeFH4stD
  youtube: https://www.youtube.com/@xforceunite2090

# Collection setting
collections:
  posts:
    output: true
  streams:
    output: true
    permalink: /streams/:name
  licencias:
    output: true
    permalink: /licencias-unite/:name

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  sass_dir: _sass
  style: compressed

include:
  - _redirects
  - .htaccess
  - assets

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
